import{a as d,S as f,i as s}from"./assets/vendor-DA0uMjGz.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();function m(i){return d.get("https://pixabay.com/api/",{params:{key:"52255318-c301db47a64feee351027f4f6",q:i,image_type:"photo",orientation:"horizontal",safesearch:"true"}})}var p=new f(".gallery a",{captionData:"alt"});const u=document.querySelector(".gallery");function g(i){let e=[];i.map(o=>{e.push(`
      <a href="${o.largeImageURL}" class="gallery-item" style="background-image: url('${o.webformatURL}')">
        <ul class="gallery-item-info">
          <li>Likes<br><span>${o.likes}</span></li>
          <li>Views<br><span>${o.views}</span></li>
          <li>Comments<br><span>${o.comments}</span></li>
          <li>Downloads<br><span>${o.downloads}</span></li>
        </ul>
      </a>
    `)}),u.innerHTML=e.join(""),p.refresh()}function y(){u.innerHTML=""}function h(){document.querySelector(".loader").classList.remove("hidden")}function l(){document.querySelector(".loader").classList.add("hidden")}const L=document.querySelector(".form"),c=document.querySelector(".formInput");L.addEventListener("submit",i=>{i.preventDefault(),c.value.trim()==""?s.warning({title:"😱",message:"Enter text in input",position:"topRight"}):(y(),h(),m(c.value).then(e=>e.data).then(e=>{e.hits.length==0?(s.warning({title:"⛔",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l()):(g(e.hits),l())}).catch(e=>console.log(e)))});const w=async()=>{console.log("Before await");let e=await new Promise(o=>{setTimeout(()=>o(5),2e3)});console.log("After await",e)};w();
//# sourceMappingURL=index.js.map
