import{a as p,S as q,i as l}from"./assets/vendor-DA0uMjGz.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&d(s)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();async function f(i,r=1){try{return(await p.get("https://pixabay.com/api/",{params:{key:"52255318-c301db47a64feee351027f4f6",q:i,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:"15",page:r}})).data}catch(e){console.log(`Problem ${e}`)}}var M=new q(".gallery a",{captionData:"alt"});const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),g=document.querySelector(".loadMore");function h(i){let r=i.map(e=>`
      <a href="${e.largeImageURL}" class="gallery-item" style="background-image: url('${e.webformatURL}')">
        <ul class="gallery-item-info">
          <li>Likes<br><span>${e.likes}</span></li>
          <li>Views<br><span>${e.views}</span></li>
          <li>Comments<br><span>${e.comments}</span></li>
          <li>Downloads<br><span>${e.downloads}</span></li>
        </ul>
      </a>
    `).join("");m.insertAdjacentHTML("beforeend",r),M.refresh()}function P(){m.innerHTML=""}function L(){y.classList.remove("hidden")}function c(){y.classList.add("hidden")}function w(){g.classList.remove("hidden")}function u(){g.classList.add("hidden")}const R=document.querySelector(".form"),n=document.querySelector(".formInput"),$=document.querySelector(".loadMore");let b,v,S,a;R.addEventListener("submit",async i=>{if(i.preventDefault(),u(),a=1,n.value.trim()=="")l.warning({title:"😱",message:"Enter text in input",position:"topRight"});else{S=n.value,P(),L();let e=await f(n.value,a);v=Math.ceil(e.totalHits/15),e.hits.length==0?(l.warning({title:"⛔",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),c()):(h(e.hits),c(),w())}b=document.querySelector(".gallery-item").getBoundingClientRect().height});$.addEventListener("click",async i=>{i.preventDefault(),u(),L();let r=await f(S,++a);c(),w(),h(r.hits),a>v&&(l.warning({title:"⛔",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),u()),window.scrollBy({top:b*2.5+48,behavior:"smooth"})});const O=async()=>{await p.get("https://jsonplaceholder.typicode.com/posts?_limit=5")};O();
//# sourceMappingURL=index.js.map
