import{a as u,S as p,i as a}from"./assets/vendor-DA0uMjGz.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();function f(r){return u.get("https://pixabay.com/api/",{params:{key:"52255318-c301db47a64feee351027f4f6",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true"}})}var m=new p(".gallery a",{captionData:"alt"});const d=document.querySelector(".gallery");function g(r){let t=[];r.map(s=>{t.push(`
      <a href="${s.largeImageURL}" class="gallery-item" style="background-image: url('${s.webformatURL}')">
        <ul class="gallery-item-info">
          <li>Likes<br><span>${s.likes}</span></li>
          <li>Views<br><span>${s.views}</span></li>
          <li>Comments<br><span>${s.comments}</span></li>
          <li>Downloads<br><span>${s.downloads}</span></li>
        </ul>
      </a>
    `)}),d.innerHTML=t.join(""),m.refresh()}function h(){d.innerHTML=""}function y(){document.querySelector(".loader").classList.remove("hidden")}function l(){document.querySelector(".loader").classList.add("hidden")}const L=document.querySelector(".form"),c=document.querySelector(".formInput");L.addEventListener("submit",r=>{r.preventDefault(),c.value.trim()==""?a.warning({title:"😱",message:"Enter text in input",position:"topRight"}):(h(),y(),f(c.value).then(t=>(console.log(t),t.data)).then(t=>{t.hits.length==0?(a.warning({title:"⛔",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l()):(g(t.hits),l())}).catch(t=>console.log(t)))});const b=async()=>{const r=await u.get("https://jsonplaceholder.typicode.com/posts?_limit=5");console.log("Posts: ",r.data)};b();
//# sourceMappingURL=index.js.map
